/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Objects;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
//    @Test void TestReadArg() throws IOException {
//        App classUnderTest = new App();
//        String[] args = {"panda.bmp","panda"};
//        String filename1 = Objects.requireNonNull(Thread.currentThread().getContextClassLoader()
//                .getResource(args[0])).getFile();
//
//        BufferedImage img = ImageIO.read(new File(filename1));
//        Bitmap image = new Bitmap(img,args[1]);
//    }
}
