/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;
import bitmap.transformer.Bitmap;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Objects;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
       // System.out.println(new App().getGreeting());
        String filename1 = Objects.requireNonNull(Thread.currentThread().getContextClassLoader()
                .getResource(args[0])).getFile();
      //  String filename1 = "/mnt/c/Users/HP/IdeaProjects/Labwork_level2/bitmap-transformer/app/src/main/resources/"+args[0];
        BufferedImage img = ImageIO.read(new File(filename1));
        Bitmap image = new Bitmap(img,args[1]);
        if(args.length !=3){
            System.out.println("The command line must has 3 arguments 'input output transform'");
        }else if(args[2].equals("Darker") ){
            image.darker();
        }else if(args[2].equals("GrayScale")){
            image.Gray();
        }else if(args[2].equals("Lighter")) {
            image.Lighter();
        }else if(args[2].equals("Mirror")){
                image.Mirror();
        }else {
            System.out.println("Please chose one of the / Darker GrayScale  Lighter or Mirror / ");
        }


    }
}
